# SITE CONFIGURATION
remote_theme: sylhare/Type-on-Strap@v2.2.1

# THEME-SPECIFIC CONFIGURATION
title: fraulyoner.de
description: "Inspiration und Tipps zu Handlettering, Sketchnotes und Flipchart-Gestaltung"
avatar: assets/img/fraulyoner-title.png
favicon: assets/favicon.ico

# HEADER AND FOOTER TEXT
header_text: "Hi, ich bin Frau Lyoner."
header_feature_image: #/assets/img/lineart.png

# BLOG
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true

# PAGINATION
paginate: 3
paginate_path: "/blog/page:num"

# FEATURES
katex:                                             # Enable if using math markup
google_analytics:                                  # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                  # Your discus shortname for comments
layout_variables:                                  # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:  true                                # In _data/social.yml
share_buttons:                                     # In _data/social.yml
authors:                                           # In _data/authors.yml
language:                                          # In _data/language.yml

# EXCLUDE from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
